# Generated by Django 3.0.4 on 2020-03-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_auto_20200323_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='citation',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='journal',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='mini_citation',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='pubmed_url',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='url',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
