# Generated by Django 3.0.4 on 2020-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_auto_20200323_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedimportedarticle',
            name='tagged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
