# Generated by Django 3.0.4 on 2020-03-24 16:06

from django.db import migrations


def load_fixture(apps, schema_editor):
    article_tags_model = apps.get_model("tagging", "ArticleTag")
    article_model = apps.get_model("screening", "PubmedImportedArticle")
    article_tags = article_tags_model.objects.all()

    for at in article_tags:
        article = article_model.objects.get(pk=at.article_id)
        article.tagged = True
        article.save()


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    # taggroup_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_pubmedimportedarticle_tagged'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
