# Generated by Django 3.0.4 on 2020-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0004_auto_20200324_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('css_class', models.CharField(max_length=30)),
            ],
        ),
    ]
