# Generated by Django 3.0.4 on 2020-03-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('highlight_type', models.CharField(choices=[('E', 'Exclude'), ('I', 'Include')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PubmedImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(verbose_name='date imported')),
                ('search_function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PubmedImportedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('screened', models.BooleanField()),
                ('doi', models.CharField(max_length=50)),
                ('import_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.PubmedImport')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('U', 'Unclear')], max_length=1)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.PubmedImportedArticle')),
            ],
        ),
    ]
