# Generated by Django 3.0.4 on 2020-03-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubmedimportedarticle',
            name='doi',
        ),
    ]
