# Generated by Django 3.0.4 on 2020-03-24 14:02

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'taggroups', app_label='tagging')

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    taggroup_model = apps.get_model("tagging", "TagGroup")
    taggroup_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_auto_20200324_1451'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
